POST http://localhost:5001/api/users/signup
Content-Type: application/json

{
    "firstName": "Kamal Preet",
    "lastName": "Singh",
    "userName": "itachii",
    "email": "kamalpreetsingh@gmail.com",
    "password": "kamalpreet1122"
}