POST https://creartivity.onrender.com/api/users/signup
Content-Type: application/json

{
    "firstName": "Kamal Preet",
    "lastName": "Singh",
    "userName": "itachii",
    "email": "kamalpreetsingghh@gmail.com",
    "password": "Music@life123"
}